# Generated by Django 5.2.17 on 2026-08-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EVT', 'Eventos'), ('STD', 'Venta de stands'), ('VIS', 'Visitas escolares')], max_length=3)),
                ('nombre', models.CharField(help_text='Lo que ve el participante. Con dos del mismo tipo, es lo único que las distingue.', max_length=160)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='borrador', max_length=10)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'convocatoria',
                'verbose_name_plural': 'convocatorias',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
