# Generated by Django 5.2.17 on 2026-08-27 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='nombre',
            field=models.CharField(help_text='Lo que ve el participante. Con dos del mismo tipo, es lo único que las distingue.', max_length=160, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='convocatoria',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_apertura__isnull', True), ('fecha_cierre__isnull', True), ('fecha_cierre__gt', models.F('fecha_apertura')), _connector='OR'), name='cierre_posterior_a_apertura'),
        ),
    ]
