# Generated by Django 5.2.17 on 2026-08-27 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_invariantes_de_convocatoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='convocatorias.convocatoria')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_convocatoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro en convocatoria',
                'verbose_name_plural': 'registros en convocatorias',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('convocatoria', 'persona'), name='un_registro_por_persona_y_convocatoria')],
            },
        ),
    ]
