# Generated by Django 5.2.17 on 2026-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionotp',
            name='acertado',
            field=models.BooleanField(default=False),
        ),
    ]
