# Generated by Django 5.2.17 on 2026-08-28 02:44

import comun.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_retirar_rolpermiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_apellido',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[comun.validadores.telefono]),
        ),
    ]
