# Generated by Django 5.2.17 on 2026-08-31 20:53

"""Dónde vive la persona, dentro de México.

Las dos nacen en blanco y así se quedan en las cuentas que ya existen:
nunca se les preguntó, y rellenarlas con una suposición —«todos son de
Yucatán»— sería inventarse un dato en la ficha de gente real.

`estado` solo cambia de `verbose_name` («estado de la cuenta»): ahora
convive con un campo cuya etiqueta es «estado», y en el admin las dos se
llamaban igual.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_validaciones_de_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='entidad',
            field=models.CharField(blank=True, choices=[('YUC', 'Yucatán'), ('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('CMX', 'Ciudad de México'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DUR', 'Durango'), ('MEX', 'Estado de México'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('ZAC', 'Zacatecas')], max_length=3, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10, verbose_name='estado de la cuenta'),
        ),
    ]
