# Generated by Django 5.2.17 on 2026-08-27 22:18

import comun.almacenamiento
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('domicilio_calle', models.CharField(max_length=160)),
                ('domicilio_numero', models.CharField(max_length=40)),
                ('domicilio_colonia', models.CharField(max_length=120)),
                ('cp', models.CharField(max_length=10, verbose_name='código postal')),
                ('municipio', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('pais', models.CharField(default='México', max_length=80, verbose_name='país')),
                ('director_general_nombre', models.CharField(max_length=160)),
                ('director_general_email', models.EmailField(max_length=254)),
                ('director_comercial_nombre', models.CharField(blank=True, max_length=160)),
                ('director_comercial_email', models.EmailField(blank=True, max_length=254)),
                ('director_editorial_nombre', models.CharField(blank=True, max_length=160)),
                ('director_editorial_email', models.EmailField(blank=True, max_length=254)),
                ('director_promocion_nombre', models.CharField(blank=True, max_length=160)),
                ('director_promocion_email', models.EmailField(blank=True, max_length=254)),
                ('responsable_stand', models.CharField(max_length=160)),
                ('giro', models.CharField(choices=[('editor', 'Editor'), ('librero', 'Librero'), ('distribuidor', 'Distribuidor')], max_length=12)),
                ('telefono_oficina', models.CharField(blank=True, max_length=20)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nombre_antepecho', models.CharField(help_text='Lo que se rotula en el antepecho del stand.', max_length=120)),
                ('num_personas_atienden', models.PositiveSmallIntegerField(default=1)),
                ('total_sellos', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_libros_aprox', models.PositiveIntegerField(default=0)),
                ('cantidad_titulos_aprox', models.PositiveIntegerField(default=0)),
                ('materiales', models.JSONField(blank=True, default=list)),
                ('tematicas', models.JSONField(blank=True, default=list)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(help_text='Quién presenta y administra esta editorial en esta feria.', on_delete=django.db.models.deletion.PROTECT, related_name='editorial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'editorial',
                'verbose_name_plural': 'editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_editorial', models.JSONField(default=dict, editable=False)),
                ('sellos', models.JSONField(default=list, editable=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cambios_solicitados', 'Cambios solicitados')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_peticion', models.TextField(blank=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='stands.editorial')),
                ('registro', models.ForeignKey(help_text='La inscripción de esta persona a esta convocatoria (FER).', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_stands', to='convocatorias.registroconvocatoria')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_stands_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aplicacion_aceptada', 'Solicitud aceptada'), ('aplicacion_rechazada', 'Solicitud rechazada'), ('aplicacion_cambios', 'Cambios solicitados'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_pagada', 'Reserva pagada'), ('posible_cancelacion', 'Posible cancelación'), ('reserva_cancelada', 'Reserva cancelada')], max_length=24)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('fallida', 'Fallida')], max_length=8)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('detalle_error', models.TextField(blank=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_stands', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='stands.solicitud')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('constancia_fiscal', 'Constancia de situación fiscal'), ('lista_titulos', 'Lista de títulos'), ('carta_representacion', 'Carta de representación'), ('comprobante_pago', 'Comprobante de pago'), ('doc_abono', 'Documento de abono'), ('otro', 'Otro')], max_length=24)),
                ('archivo', models.FileField(upload_to=comun.almacenamiento.CarpetaDeLaFeria('documentos'))),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='stands.editorial')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='stands.solicitud')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='costo por m²')),
                ('porcentaje_anticipo', models.PositiveSmallIntegerField(default=50, help_text='Cuánto hay que abonar para confirmar la reserva (RN-02).', verbose_name='porcentaje de anticipo')),
                ('plazo_reserva_dias', models.PositiveSmallIntegerField(default=30, help_text='Vigencia de una reserva en espera del anticipo (RN-03).', verbose_name='plazo de la reserva (días)')),
                ('descuento_pronto_pago', models.PositiveSmallIntegerField(default=10, help_text='10% por omisión, configurable (RN-04).', verbose_name='descuento por pronto pago (%)')),
                ('fecha_limite_pronto_pago', models.DateField(blank=True, null=True)),
                ('instrucciones_pago', models.TextField(blank=True, help_text='Banco, cuenta, CLABE, sucursal y referencia.')),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_stands', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'configuración de la convocatoria',
                'verbose_name_plural': 'configuraciones de convocatoria',
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje_anticipo__lte', 100)), name='el_anticipo_no_pasa_del_100'), models.CheckConstraint(condition=models.Q(('descuento_pronto_pago__lte', 100)), name='el_pronto_pago_no_pasa_del_100')],
            },
        ),
        migrations.CreateModel(
            name='SelloEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellos', to='stands.editorial')),
            ],
            options={
                'verbose_name': 'sello editorial',
                'verbose_name_plural': 'sellos editoriales',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('editorial', 'nombre'), name='un_sello_no_se_declara_dos_veces')],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('pendiente', 'cambios_solicitados'))), fields=('registro',), name='una_solicitud_viva_por_registro'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ('pendiente', 'cambios_solicitados')), ('fecha_revision__isnull', False), _connector='OR'), name='una_solicitud_resuelta_tiene_fecha_de_revision'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('editorial__isnull', False), ('solicitud__isnull', True)), models.Q(('editorial__isnull', True), ('solicitud__isnull', False)), _connector='OR'), name='un_documento_cuelga_de_exactamente_una_entidad'),
        ),
    ]
