# Generated by Django 5.2.17 on 2026-08-27 22:44

import comun.almacenamiento
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=comun.almacenamiento.CarpetaDeLaFeria('documentos'), validators=[comun.almacenamiento.DocumentoAdmisible()]),
        ),
    ]
