# Generated by Django 5.2.17 on 2026-08-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='sello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='stands.selloeditorial'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('sello__isnull', True), ('tipo', 'carta_representacion'), _connector='OR'), name='solo_una_carta_cuelga_de_un_sello'),
        ),
    ]
