# Generated by Django 5.2.17 on 2026-08-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_documento_sello_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='fecha_limite_pronto_pago',
            field=models.DateField(blank=True, null=True, verbose_name='fecha límite del pronto pago'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre original del archivo'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='cantidad_libros_aprox',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad aproximada de libros'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='cantidad_titulos_aprox',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad aproximada de títulos'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='correo de contacto'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_comercial_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo del director comercial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_comercial_nombre',
            field=models.CharField(blank=True, max_length=160, verbose_name='director comercial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_editorial_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo del director editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_editorial_nombre',
            field=models.CharField(blank=True, max_length=160, verbose_name='director editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_general_email',
            field=models.EmailField(max_length=254, verbose_name='correo del director general'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_general_nombre',
            field=models.CharField(max_length=160, verbose_name='director general'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_promocion_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo del director de promoción'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='director_promocion_nombre',
            field=models.CharField(blank=True, max_length=160, verbose_name='director de promoción'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='domicilio_calle',
            field=models.CharField(max_length=160, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='domicilio_colonia',
            field=models.CharField(max_length=120, verbose_name='colonia'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='domicilio_numero',
            field=models.CharField(max_length=40, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='estado',
            field=models.CharField(max_length=120, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='giro',
            field=models.CharField(choices=[('editor', 'Editor'), ('librero', 'Librero'), ('distribuidor', 'Distribuidor')], max_length=12, verbose_name='giro'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='materiales',
            field=models.JSONField(blank=True, default=list, verbose_name='materiales que exhibe'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='municipio',
            field=models.CharField(max_length=120, verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre de la editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre_antepecho',
            field=models.CharField(help_text='Lo que se rotula en el antepecho del stand.', max_length=120, verbose_name='nombre en el antepecho'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='num_personas_atienden',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='personas que atienden el stand'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='responsable_stand',
            field=models.CharField(max_length=160, verbose_name='responsable del stand'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono_celular',
            field=models.CharField(max_length=20, verbose_name='teléfono celular'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono de oficina'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='tematicas',
            field=models.JSONField(blank=True, default=list, verbose_name='temáticas'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='total_sellos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total de sellos'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='detalle_error',
            field=models.TextField(blank=True, verbose_name='detalle del error'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='motivo_peticion',
            field=models.TextField(blank=True, verbose_name='motivo o cambios pedidos'),
        ),
    ]
