# Generated by Django 5.2.17 on 2026-08-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_alter_configuracionsistema_fecha_limite_pronto_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='materiales_otro',
            field=models.CharField(blank=True, max_length=160, verbose_name='¿qué otro material?'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='tematicas_otra',
            field=models.CharField(blank=True, max_length=160, verbose_name='¿qué otra temática?'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='bases_aceptadas',
            field=models.BooleanField(default=False, verbose_name='aceptó las bases'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre_antepecho',
            field=models.CharField(help_text='Se rotula tal como lo escribas. Cambiarlo después de que se imprima tiene un costo que corre por tu cuenta.', max_length=120, verbose_name='nombre en el antepecho'),
        ),
    ]
