# Generated by Django 5.2.17 on 2026-08-28 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0006_pais_como_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='plazo_reserva_dias',
            field=models.PositiveSmallIntegerField(default=30, help_text='Vigencia de una reserva en espera del anticipo (RN-03).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='plazo de la reserva (días)'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='nombre de la editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='num_personas_atienden',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='personas que atienden el stand'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono_celular',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Escribe el teléfono con clave lada, solo números (por ejemplo, 999 123 4567).', regex='^\\+?[\\d\\s().-]{8,}$')], verbose_name='teléfono celular'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Escribe el teléfono con clave lada, solo números (por ejemplo, 999 123 4567).', regex='^\\+?[\\d\\s().-]{8,}$')], verbose_name='teléfono de oficina'),
        ),
    ]
