# Generated by Django 5.2.17 on 2026-08-28 22:20

import comun.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0007_validaciones_de_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='telefono_celular',
            field=models.CharField(max_length=20, validators=[comun.validadores.telefono], verbose_name='teléfono celular'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=20, validators=[comun.validadores.telefono], verbose_name='teléfono de oficina'),
        ),
    ]
