# Generated by Django 5.2.17 on 2026-08-29 04:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('stands', '0008_alter_editorial_telefono_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaShowfloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.CharField(help_text='Recinto donde se monta este showfloor.', max_length=160, verbose_name='salón')),
                ('columnas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('filas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('metros_por_celda', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='metros por celda')),
                ('tamano_celda', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tamaño de la celda (px)')),
                ('importado_en', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapa_showfloor', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'mapa del showfloor',
                'verbose_name_plural': 'mapas del showfloor',
            },
        ),
        migrations.CreateModel(
            name='DecoracionMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rectangulo', 'Rectángulo'), ('texto', 'Texto')], max_length=12)),
                ('col', models.PositiveSmallIntegerField()),
                ('fila', models.PositiveSmallIntegerField()),
                ('ancho_celdas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alto_celdas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('etiqueta', models.CharField(max_length=120)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoraciones', to='stands.mapashowfloor')),
            ],
            options={
                'verbose_name': 'decoración del mapa',
                'verbose_name_plural': 'decoraciones del mapa',
                'ordering': ['fila', 'col'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alto_celdas__isnull', True), ('ancho_celdas__isnull', True), ('tipo', 'texto')), models.Q(('alto_celdas__isnull', False), ('ancho_celdas__isnull', False), ('tipo', 'rectangulo')), _connector='OR'), name='un_rectangulo_tiene_medidas_y_un_texto_no')],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='clave')),
                ('etiqueta', models.CharField(help_text='Lo que se pinta dentro de la caja en el mapa.', max_length=60, verbose_name='etiqueta')),
                ('zona', models.CharField(blank=True, max_length=80, verbose_name='zona')),
                ('col', models.PositiveSmallIntegerField()),
                ('fila', models.PositiveSmallIntegerField()),
                ('ancho_celdas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alto_celdas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rectangulos', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='disponible', max_length=12)),
                ('incluye', models.TextField(blank=True, help_text='Estructura, contactos, exhibidores, mobiliario…', verbose_name='qué incluye')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='stands.mapashowfloor')),
            ],
            options={
                'verbose_name': 'stand',
                'verbose_name_plural': 'stands',
                'ordering': ['fila', 'col'],
                'constraints': [models.UniqueConstraint(fields=('mapa', 'clave'), name='una_clave_por_mapa'), models.CheckConstraint(condition=models.Q(models.Q(('alto_celdas__isnull', False), ('ancho_celdas__isnull', False), ('rectangulos__isnull', True)), models.Q(('alto_celdas__isnull', True), ('ancho_celdas__isnull', True), ('rectangulos__isnull', False)), _connector='OR'), name='un_stand_es_rectangular_o_irregular')],
            },
        ),
    ]
