# Generated by Django 5.2.17 on 2026-08-29 05:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('stands', '0009_mapa_del_showfloor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('por_confirmar', 'Por confirmar'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='por_confirmar', max_length=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_anticipo', models.DateTimeField(verbose_name='vencimiento del anticipo')),
                ('fecha_corte_pago_total', models.DateTimeField(blank=True, null=True, verbose_name='corte del pago total')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto total')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='stands.editorial')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='convocatorias.registroconvocatoria')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pronto_pago', 'Pronto pago'), ('especial', 'Especial')], max_length=12)),
                ('porcentaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_aplicados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='stands.reserva')),
            ],
            options={
                'verbose_name': 'descuento aplicado',
                'verbose_name_plural': 'descuentos aplicados',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('reserva', 'tipo'), name='un_descuento_de_cada_tipo'), models.CheckConstraint(condition=models.Q(('tipo', 'pronto_pago'), models.Q(('motivo', ''), _negated=True), _connector='OR'), name='un_descuento_especial_lleva_motivo'), models.CheckConstraint(condition=models.Q(('porcentaje__lte', 100)), name='un_descuento_no_pasa_del_100')],
            },
        ),
        migrations.CreateModel(
            name='ReservaStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='stands.reserva')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_de_reserva', to='stands.stand')),
            ],
            options={
                'verbose_name': 'stand de la reserva',
                'verbose_name_plural': 'stands de la reserva',
                'ordering': ['stand__fila', 'stand__col'],
                'constraints': [models.UniqueConstraint(fields=('reserva', 'stand'), name='un_stand_una_vez_por_reserva')],
            },
        ),
    ]
