# Generated by Django 5.2.17 on 2026-08-29 15:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0010_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('cheque', 'Cheque')], max_length=14, verbose_name='método de pago')),
                ('origen', models.CharField(choices=[('aplicante', 'Lo registró el aplicante'), ('admin_manual', 'Lo registró la administración')], max_length=12)),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente_validacion', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stands.documento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stands.reserva')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'ordering': ['-fecha_registro'],
                'constraints': [models.CheckConstraint(condition=models.Q(('origen', 'aplicante'), ('comprobante__isnull', False), _connector='OR'), name='un_abono_manual_lleva_comprobante'), models.CheckConstraint(condition=models.Q(('estado', 'pendiente_validacion'), models.Q(('fecha_validacion__isnull', False), ('validado_por__isnull', False)), _connector='OR'), name='un_movimiento_resuelto_dice_quien_y_cuando')],
            },
        ),
    ]
