# Generated by Django 5.2.17 on 2026-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('stands', '0011_movimiento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('por_confirmar', 'confirmada', 'pagada'))), fields=('registro',), name='una_reserva_viva_por_registro'),
        ),
    ]
