# Generated by Django 5.2.17 on 2026-08-29 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0012_una_reserva_por_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_clabe',
            field=models.CharField(blank=True, help_text='18 dígitos. Se admiten espacios.', max_length=40, validators=[django.core.validators.RegexValidator(message='La CLABE lleva 18 dígitos.', regex='^(?:\\s*\\d){18}\\s*$')], verbose_name='CLABE'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_cuenta',
            field=models.CharField(blank=True, max_length=40, verbose_name='número de cuenta'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=80, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_referencia',
            field=models.CharField(blank=True, help_text='Qué debe escribir la editorial al pagar. Ejemplo: su nombre.', max_length=160, verbose_name='concepto o referencia'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_sucursal',
            field=models.CharField(blank=True, max_length=120, verbose_name='sucursal'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco_titular',
            field=models.CharField(blank=True, help_text='A nombre de quién se hace la transferencia.', max_length=160, verbose_name='titular de la cuenta'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='instrucciones_pago',
            field=models.TextField(blank=True, help_text='Lo que haga falta decir además de los datos de la cuenta.', verbose_name='instrucciones adicionales'),
        ),
    ]
