# Generated by Django 5.2.17 on 2026-08-30 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0013_datos_bancarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='fecha_corte_pago_total',
            field=models.DateField(blank=True, help_text='Hasta cuándo hay para liquidar. La hereda cada reserva al confirmarse; después se puede ajustar una por una.', null=True, verbose_name='fecha de corte del pago total'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='stands.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_corte_pago_total',
            field=models.DateField(blank=True, null=True, verbose_name='corte del pago total'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reserva__isnull', True), ('solicitud__isnull', False)), models.Q(('reserva__isnull', False), ('solicitud__isnull', True)), _connector='OR'), name='un_aviso_cuelga_de_exactamente_una_cosa'),
        ),
    ]
