# Generated by Django 5.2.17 on 2026-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0014_avisos_de_la_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('aplicacion_aceptada', 'Solicitud aceptada'), ('aplicacion_rechazada', 'Solicitud rechazada'), ('aplicacion_cambios', 'Cambios solicitados'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_pagada', 'Reserva pagada'), ('posible_cancelacion', 'Posible cancelación'), ('reserva_cancelada', 'Reserva cancelada'), ('reserva_vencida', 'Reserva vencida (a quien administra)')], max_length=24),
        ),
    ]
