# Generated by Django 5.2.17 on 2026-08-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('stands', '0016_cancelar_una_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('abono_manual', 'Asentó un abono manual'), ('abono_validado', 'Validó un abono'), ('abono_rechazado', 'Rechazó un abono'), ('descuento_aplicado', 'Aplicó un descuento especial'), ('descuento_retirado', 'Retiró el descuento especial'), ('pronto_pago_caducado', 'Caducó el pronto pago'), ('reserva_prorrogada', 'Prorrogó el plazo'), ('corte_movido', 'Movió el corte del pago total'), ('reserva_cancelada', 'Canceló la reserva'), ('solicitud_dictaminada', 'Dictaminó una solicitud'), ('configuracion_cambiada', 'Cambió la configuración'), ('mapa_importado', 'Importó el mapa')], max_length=24)),
                ('entidad_tipo', models.CharField(max_length=20)),
                ('entidad_id', models.PositiveIntegerField()),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_stands', to='convocatorias.convocatoria')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_stands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de bitácora',
                'verbose_name_plural': 'bitácora de stands',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['entidad_tipo', 'entidad_id'], name='stands_bita_entidad_31d81e_idx'), models.Index(fields=['convocatoria', '-fecha'], name='stands_bita_convoca_035139_idx'), models.Index(fields=['-fecha'], name='stands_bita_fecha_6398ec_idx')],
            },
        ),
    ]
