# Generated by Django 5.2.17 on 2026-08-30 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('stands', '0017_bitacora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitud',
            name='una_solicitud_viva_por_registro',
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ('pendiente', 'cambios_solicitados', 'aceptada'))), fields=('registro',), name='una_solicitud_en_juego_por_registro'),
        ),
    ]
