# Generated by Django 5.2.17 on 2026-08-31 20:30

"""A qué buzón salió cada aviso, y con qué acuse del proveedor.

Los avisos ya existentes se quedan con los dos campos vacíos: la
dirección que se usó entonces no se puede reconstruir —sale de la ficha,
que se puede haber corregido después—, y ese es justamente el motivo de
guardarla a partir de ahora.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0018_una_solicitud_en_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='destino',
            field=models.EmailField(blank=True, max_length=254, verbose_name='dirección de destino'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=120, verbose_name='acuse del proveedor'),
        ),
    ]
