# Generated by Django 5.2.17 on 2026-08-25 21:48

import apps.ferias.models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(help_text='P. ej. «FILEY 2027».', max_length=120)),
                ('edicion', models.CharField(blank=True, help_text='Ordinal de la edición, p. ej. «XIV». Sale en constancias y programa.', max_length=20)),
                ('slug', models.SlugField(help_text='Prefijo de la URL (/f/2027/) y raíz del schema. No cambia nunca.', max_length=57, unique=True, validators=[apps.ferias.models.validar_slug])),
                ('estado', models.CharField(choices=[('en_preparacion', 'En preparación'), ('activa', 'Activa'), ('archivada', 'Archivada')], default='en_preparacion', max_length=15)),
                ('sede', models.CharField(blank=True, help_text='Recinto de la edición entera, no el salón de cada cosa.', max_length=180)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'feria',
                'verbose_name_plural': 'ferias',
                'ordering': ['-creada_en'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ferias.feria')),
            ],
            options={
                'verbose_name': 'slug de ruteo',
                'verbose_name_plural': 'slugs de ruteo',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminFeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_dueno', models.BooleanField(default=False, help_text='El dueño es el único que da de alta administradores y convocatorias.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Nulo en el dueño: lo designó el operador desde fuera de la feria.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_concedidos', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_admin', to=settings.AUTH_USER_MODEL)),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='ferias.feria')),
            ],
            options={
                'verbose_name': 'acceso a feria',
                'verbose_name_plural': 'accesos a ferias',
                'ordering': ['-es_dueno', 'creado_en'],
                'constraints': [models.UniqueConstraint(fields=('feria', 'persona'), name='acceso_unico_por_feria_y_persona'), models.UniqueConstraint(condition=models.Q(('es_dueno', True)), fields=('feria',), name='un_solo_dueno_por_feria')],
            },
        ),
    ]
