# Generated by Django 5.2.17 on 2026-08-31 15:56

"""El pie de página, declarable por edición.

Los tres campos nacen en blanco, y en blanco significa heredar de
`settings.PIE_*`: ninguna feria existente cambia de pie al migrar.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_feria_de_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='feria',
            name='pie_contacto',
            field=models.CharField(blank=True, help_text='Dirección y correo, en el segundo renglón. En blanco, el de la plataforma.', max_length=240, verbose_name='pie · contacto'),
        ),
        migrations.AddField(
            model_name='feria',
            name='pie_dependencia',
            field=models.CharField(blank=True, help_text='Quién organiza, tras el nombre. En blanco, el de la plataforma.', max_length=180, verbose_name='pie · dependencia'),
        ),
        migrations.AddField(
            model_name='feria',
            name='pie_entidad',
            field=models.CharField(blank=True, help_text='El nombre en negritas. En blanco, el de la plataforma.', max_length=60, verbose_name='pie · entidad'),
        ),
    ]
