# Generated by Django 5.2.17 on 2026-09-01 19:40

import comun.almacenamiento
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='CatalogoActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('conversatorio', 'Conversatorio'), ('conferencia', 'Conferencia'), ('charla', 'Charla'), ('mesa_redonda', 'Mesa redonda'), ('presentacion_libro', 'Presentación de libro'), ('presentacion_revista', 'Presentación de revista'), ('lectura_obra', 'Lectura de obra'), ('encuentro', 'Encuentro')], max_length=25, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'verbose_name_plural': 'tipos de actividad',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActividadCharla',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
            ],
            options={
                'verbose_name': 'charla',
                'verbose_name_plural': 'charlas',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadConferencia',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
            ],
            options={
                'verbose_name': 'conferencia',
                'verbose_name_plural': 'conferencias',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadConversatorio',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
                ('nombre_participante_3', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 3')),
                ('semblanza_participante_3', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 3')),
            ],
            options={
                'verbose_name': 'conversatorio',
                'verbose_name_plural': 'conversatorios',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadEncuentro',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
            ],
            options={
                'verbose_name': 'encuentro',
                'verbose_name_plural': 'encuentros',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadLecturaObra',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
            ],
            options={
                'verbose_name': 'lectura de obra',
                'verbose_name_plural': 'lecturas de obra',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadMesaRedonda',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('nombre_participante_1', models.CharField(max_length=160, verbose_name='nombre del participante 1')),
                ('semblanza_participante_1', models.TextField(max_length=2000, verbose_name='semblanza del participante 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 2')),
                ('nombre_participante_3', models.CharField(blank=True, max_length=160, verbose_name='nombre del participante 3')),
                ('semblanza_participante_3', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del participante 3')),
            ],
            options={
                'verbose_name': 'mesa redonda',
                'verbose_name_plural': 'mesas redondas',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadPresentacionLibro',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('titulo_publicacion', models.CharField(max_length=200, verbose_name='título del libro')),
                ('tipo_presentador', models.CharField(choices=[('autor', 'Autor/a'), ('editor', 'Editor/a'), ('antologador', 'Antologador/a'), ('compilador', 'Compilador/a'), ('coordinador', 'Coordinador/a')], max_length=15, verbose_name='el proponente es')),
                ('nombre_editorial', models.CharField(max_length=180, verbose_name='editorial')),
                ('nombre_autor_1', models.CharField(max_length=160, verbose_name='nombre del autor 1')),
                ('semblanza_autor_1', models.TextField(max_length=2000, verbose_name='semblanza del autor 1')),
                ('autor_1_participa', models.BooleanField(default=True, verbose_name='autor 1 participa')),
                ('nombre_autor_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del autor 2')),
                ('semblanza_autor_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del autor 2')),
                ('autor_2_participa', models.BooleanField(default=True, verbose_name='autor 2 participa')),
                ('nombre_autor_3', models.CharField(blank=True, max_length=160, verbose_name='nombre del autor 3')),
                ('semblanza_autor_3', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del autor 3')),
                ('autor_3_participa', models.BooleanField(default=True, verbose_name='autor 3 participa')),
                ('nombre_autor_4', models.CharField(blank=True, max_length=160, verbose_name='nombre del autor 4')),
                ('semblanza_autor_4', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del autor 4')),
                ('autor_4_participa', models.BooleanField(default=True, verbose_name='autor 4 participa')),
                ('nombre_autor_5', models.CharField(blank=True, max_length=160, verbose_name='nombre del autor 5')),
                ('semblanza_autor_5', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del autor 5')),
                ('autor_5_participa', models.BooleanField(default=True, verbose_name='autor 5 participa')),
                ('nombre_participante_1', models.CharField(blank=True, max_length=160, verbose_name='nombre del presentador 1')),
                ('semblanza_participante_1', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del presentador 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del presentador 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del presentador 2')),
            ],
            options={
                'verbose_name': 'presentación de libro',
                'verbose_name_plural': 'presentaciones de libro',
            },
            bases=('eventos.actividad',),
        ),
        migrations.CreateModel(
            name='ActividadPresentacionRevista',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.actividad')),
                ('titulo_publicacion', models.CharField(max_length=200, verbose_name='título de la revista')),
                ('tipo_presentador', models.CharField(choices=[('autor', 'Autor/a'), ('editor', 'Editor/a'), ('antologador', 'Antologador/a'), ('compilador', 'Compilador/a'), ('coordinador', 'Coordinador/a')], max_length=15, verbose_name='el proponente es')),
                ('nombre_editorial', models.CharField(max_length=180, verbose_name='editorial')),
                ('nombre_editor_1', models.CharField(max_length=160, verbose_name='nombre del editor 1')),
                ('semblanza_editor_1', models.TextField(max_length=2000, verbose_name='semblanza del editor 1')),
                ('editor_1_participa', models.BooleanField(default=True, verbose_name='editor 1 participa')),
                ('nombre_editor_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del editor 2')),
                ('semblanza_editor_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del editor 2')),
                ('editor_2_participa', models.BooleanField(default=True, verbose_name='editor 2 participa')),
                ('nombre_participante_1', models.CharField(blank=True, max_length=160, verbose_name='nombre del presentador 1')),
                ('semblanza_participante_1', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del presentador 1')),
                ('nombre_participante_2', models.CharField(blank=True, max_length=160, verbose_name='nombre del presentador 2')),
                ('semblanza_participante_2', models.TextField(blank=True, max_length=2000, verbose_name='semblanza del presentador 2')),
            ],
            options={
                'verbose_name': 'presentación de revista',
                'verbose_name_plural': 'presentaciones de revista',
            },
            bases=('eventos.actividad',),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='eventos.catalogoactividades'),
        ),
        migrations.CreateModel(
            name='ConfiguracionConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_folio', models.CharField(default='EVE', max_length=10)),
                ('convocatoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_eventos', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'configuración de la convocatoria de eventos',
                'verbose_name_plural': 'configuraciones de convocatoria de eventos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('portada_libro', 'Portada del libro'), ('portada_revista', 'Portada de la revista'), ('retrato_autor', 'Fotografía del autor/a')], max_length=20)),
                ('archivo', models.FileField(upload_to=comun.almacenamiento.CarpetaDeLaFeria('eventos'), validators=[comun.almacenamiento.DocumentoAdmisible()])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='eventos.actividad')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=180, verbose_name='dependencia o institución')),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('es_uady', models.BooleanField(default=False, verbose_name='se declara parte de la UADY')),
                ('titulo_actividad', models.CharField(max_length=200)),
                ('nombre_organizador_organizacion', models.CharField(max_length=180, verbose_name='organiza')),
                ('nombre_moderador', models.CharField(blank=True, max_length=160, verbose_name='moderador/a')),
                ('publico_objetivo', models.JSONField(default=list)),
                ('sinopsis', models.TextField(max_length=4000)),
                ('requiere_constancia', models.BooleanField(default=False, verbose_name='solicita constancia de participación')),
                ('comentarios', models.TextField(blank=True, verbose_name='comentarios u observaciones')),
                ('bases_aceptadas', models.BooleanField(default=False, verbose_name='aceptó las bases')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cambios_solicitados', 'Cambios solicitados')], default='pendiente', max_length=20)),
                ('fecha_de_solicitud', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(help_text='La inscripción de esta persona a esta convocatoria (FER).', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_eventos', to='convocatorias.registroconvocatoria')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-fecha_de_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='eventos.solicitud'),
        ),
    ]
