# Generated by Django 5.2.17 on 2026-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_los_ocho_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadpresentacionlibro',
            name='autor_1_participa',
            field=models.BooleanField(default=False, verbose_name='autor 1 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionlibro',
            name='autor_2_participa',
            field=models.BooleanField(default=False, verbose_name='autor 2 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionlibro',
            name='autor_3_participa',
            field=models.BooleanField(default=False, verbose_name='autor 3 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionlibro',
            name='autor_4_participa',
            field=models.BooleanField(default=False, verbose_name='autor 4 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionlibro',
            name='autor_5_participa',
            field=models.BooleanField(default=False, verbose_name='autor 5 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionrevista',
            name='editor_1_participa',
            field=models.BooleanField(default=False, verbose_name='editor 1 participa'),
        ),
        migrations.AlterField(
            model_name='actividadpresentacionrevista',
            name='editor_2_participa',
            field=models.BooleanField(default=False, verbose_name='editor 2 participa'),
        ),
    ]
