# Generated by Django 5.2.17 on 2026-09-03 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_participacion_no_se_da_por_supuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='categoria',
            field=models.CharField(blank=True, choices=[('literaria', 'Literaria'), ('academica', 'Académica')], max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='es_uady_confirmado',
            field=models.BooleanField(blank=True, null=True, verbose_name='la UADY, confirmado por quien revisa'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_resultado_notificado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mensaje_cambios_solicitados',
            field=models.TextField(blank=True, verbose_name='qué debe corregir'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='motivo del rechazo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='resultado_notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cambios_solicitados', 'Cambios solicitados'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
