# Generated by Django 5.2.17 on 2026-09-03 21:38

import comun.almacenamiento
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_registro_convocatoria'),
        ('eventos', '0004_el_dictamen_del_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEnEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('portada_libro', 'Portada del libro'), ('portada_revista', 'Portada de la revista'), ('retrato_autor', 'Fotografía del autor/a')], max_length=20)),
                ('archivo', models.FileField(upload_to=comun.almacenamiento.CarpetaDeLaFeria('eventos/en-espera'), validators=[comun.almacenamiento.DocumentoAdmisible()])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_en_espera', to='convocatorias.convocatoria')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_en_espera_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo en espera',
                'verbose_name_plural': 'archivos en espera',
                'ordering': ['-subido_en', '-pk'],
                'indexes': [models.Index(fields=['convocatoria', 'persona', 'tipo_documento'], name='evt_en_espera_de_quien')],
            },
        ),
    ]
