# Generated by Django 5.2.17 on 2026-09-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_archivos_en_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoenespera',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
